# Generated by Django 4.0.5 on 2022-06-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_women_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='women.women'),
        ),
    ]
